version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      platform: linux/arm/v7
    container_name: gkeep-sync-container
    env_file:
      - .env
    volumes:
      - .:/app
    command: ["python", "main.py"]
    ports:
      - "5000:5000"
