version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gkeep-sync-container
    env_file:
      - .env
    volumes:
      - .:/app
    command: ["python", "-u", "app.py"]
    ports:
      - "5000:5000"
    dns:
      - 8.8.8.8
      - 8.8.4.4
